#!/bin/sh
# athena starting script by rowla

PS="ps ax"

L_SRV="login-server"
C_SRV="char-server"
M_SRV="map-server"
L_SRV_C="./conf/login_athena.conf"
C_SRV_C="./conf/char_athena.conf"
C_SRV_C2="./conf/inter_athena.conf"
M_SRV_C="./conf/map_athena.conf"
M_SRV_C2="./conf/battle_athena.conf"


print_start()
{
#	more << EOF
echo "
Athena Starting...
			(c) 2003 Athena Project.
			URL:http://project-yare.de/

Debug informations will appear,
since this is a test release.

checking..."
#EOF
}

check_account()
{
	if [ ! -f ./account.txt ]; then
		echo "0	s1	p1	-	S	0" > account.txt
		echo "1	s2	p2	-	S	0" >>account.txt
		echo "2	s3	p3	-	S	0" >>account.txt
		echo "3	s4	p4	-	S	0" >>account.txt
		echo "4	s5	p5	-	S	0" >>account.txt
	fi
}

check_files()
{

	for i in ${L_SRV} ${C_SRV} ${M_SRV} ${L_SRV_C} ${C_SRV_C} ${C_SRV_C2} ${M_SRV_C} ${M_SRV_C2}
	do
		if [ ! -f ./$i ]; then
    		echo "$i does not exist, or can't run."
    		echo "Stoped, Check your compile or configuration file."
    		exit 1;
		fi
	done

#	more << EOF
echo "
Check done.
Looks good, have a nice athena!"
#EOF
}
	

case $1 in
	'start')
		print_start
		check_account
		check_files

		exec ./${L_SRV} ${L_SRV_C}&
#		exec ./${C_SRV} ${C_SRV_C} ${C_SRV_C2} > /dev/null&
#		exec ./${M_SRV} ${M_SRV_C} ${M_SRV_C2} > /dev/null&
		exec ./${C_SRV} ${C_SRV_C} ${C_SRV_C2}&
		exec ./${M_SRV} ${M_SRV_C} ${M_SRV_C2}&

echo "
Now Started Athena."
;;
	'stop')
		${PS} | grep -E "${L_SRV}|${C_SRV}|${M_SRV}" | awk '{print $1}' | xargs kill -9
	;;
	*)
		echo "Usage: athena-start { start | stop }"
	;;
esac
