echo Y | del char\*.o
echo Y | del char\GNUmakefile
echo Y | del common\*.o
echo Y | del common\GNUmakefile
echo Y | del login\*.o
echo Y | del login\GNUmakefile
echo Y | del map\*.o
echo Y | del map\GNUmakefile
echo Y | del login-server.exe
echo Y | del char-server.exe
echo Y | del map-server.exe
