echo Y | del src\char\*.o
echo Y | del src\char\GNUmakefile
echo Y | del src\common\*.o
echo Y | del src\common\GNUmakefile
echo Y | del src\login\*.o
echo Y | del src\login\GNUmakefile
echo Y | del src\map\*.o
echo Y | del src\map\GNUmakefile
echo Y | del bin\login-server.exe
echo Y | del bin\char-server.exe
echo Y | del bin\map-server.exe
