#!/usr/bin/perl

##########################################################################
# Athenaのログインサーバー保守ツール Ver.1.00
#
# 　起動中のAthenaのlogin.exeに接続してアカウントの保守を行うツール.
# 　アカウントの追加、削除、パスワードの変更、リスト表示ができます.
#
#-------------------------------------------------------------------------
# 設定方法
# 　ログイン鯖のIP、ポート、管理者パスワードを正しく設定します.
# 　設定後、起動するとプロンプトがでます。コマンドは後述。
# 　コマンドは最初の数文字でもかまいません
#	<例>  q  <= quit , li <= list , pass <= passwd …など
#
# 　コマンドリスト
#	quit				終了
#
#	list	[start_id [,end_id]]	アカウントリスト表示
#		start_id,end_idは共に省略可能です。
#		例> list 10 9999999
#		アカウント名での検索などはできません
#
#	add	userid gender passwd	アカウント追加
#		ID,性別,passです。性別は MかFです(最初の１文字で判断)
#		例> add testname Male testpass
#	
#	del	userid			アカウント削除
#		警告がでるのでそこでyを入力すると削除します
#
#	passwd	userid newpassword	アカウントパスワード変更
#
#	help				簡単なヘルプテキスト表示
#
##########################################################################

$loginserverip="127.0.0.1";		#ログイン鯖のIP
$loginserverport=6900;			#ログイン鯖のポート
$loginserveradminpassword="admin";	#ログイン鯖の管理者パスワード

$connecttimeout=10;	# 接続タイムアウト(秒)

#-------------------------------設定ここまで-----------------------------







use IO::Socket;

$ver="1.00";

sub flush_stdout {
	$|=1;
	$|=0;
}

print "Athena login-server administration tool Ver.$ver\n";

# サーバーに接続する
my($so,$er)=();
eval{
	$so=IO::Socket::INET->new(
		PeerAddr=> $loginserverip,
		PeerPort=> $loginserverport,
		Proto	=> "tcp",
		Timeout	=> $connecttimeout) or $er=1;
};
if($er || $@){
	print "\nCant connect to login server [${loginserverip}:$loginserverport] !\n";
	exit(2);
}

print $so pack("v3a24",0x7918,30,0,$loginserveradminpassword);
$so->flush();

# 返答待ち
my($buf)=readso(3);
if(unpack("v",$buf)!=0x7919 || unpack("x2c",$buf)!=0 ){
	print "login error. (password incorrect ?)\n";
	exit(4);
}
print "logged on.\n";

# ログインできたのでプロンプトのループ
while(1){
	# プロンプト表示と入力
	print "ALadmin> ";
	$cmd=<STDIN>;
	chomp $cmd;
	$cmd=~s/[\x00-\x1f]//g;
	my(@cmdlist)=split / /,$cmd;
	
	# コマンド解析
	eval{
		if("help"=~/^$cmdlist[0]/ ){
			print << "EOD";
  add username gender password -- add account
  del username                 -- delete account
  passwd username new_password -- change password of account
  list [start_id [end_id] ]    -- list account
  help                         -- this help
  quit                         -- quit
EOD
		}elsif("quit"=~/^$cmdlist[0]/){
			last;
		}elsif("add"=~/^$cmdlist[0]/){
			addaccount($cmdlist[1],$cmdlist[2],$cmdlist[3]);
		}elsif("del"=~/^$cmdlist[0]/){
			delaccount($cmdlist[1]);
		}elsif("passwd"=~/^$cmdlist[0]/){
			changepasswd($cmdlist[1],$cmdlist[2]);
		}elsif("list"=~/^$cmdlist[0]/){
			listaccount(int($cmdlist[1]),int($cmdlist[2]));
		}elsif($cmdlist[0]){
			print "Unknown command [".$cmdlist[0]."]\n";
		}
	};
	if($@){
		print "Error [".$cmdlist[0]."]\n$@";
	}
};

# 終了処理
print $so pack("v",0x7532);
$so->flush();

print "bye.\n";
exit(0);



#--------------------------------------------------------------------------

# アカウントリスト表示
sub listaccount(){
	my($st,$ed)= @_;
	print $so pack("vV2c",0x7920,$st,$ed,0);
	$so->flush();
	$buf=readso(4);
	if(unpack("v",$buf)!=0x7921){
		print "List failed.\n";
		exit(10);
	}
	#      0123456789 012345678901234567890123 012345 
	print "account_id user_id                  Gender Login-count\n";
	print "------------------------------------------------------\n";
	my($i);
	my($len)=unpack("x2v",$buf);
	for($i=4;$i<$len;$i+=57){
		my(@dat)=unpack("Va24ca24V",readso(57));
		printf "%10d %-24s %s %d\n",$dat[0],$dat[1],
			("Male  ","Female","Server")[$dat[2]],$dat[4];
	}
	return 0;
}
# アカウント追加
sub addaccount(){
	my($userid,$sex,$passwd)= @_;
	if($userid=~/[^A-Za-z0-9\@-_]/){
		print "Illeagal charactor found in user_id ".$`."[${&}]${'}\n";
		return;
	}
	if(length($userid)<4 || length($userid)>24){
		print "Account id too short or long. please input 4-24bytes.\n";
		return;
	}
	$sex=uc(substr($sex,0,1));
	if( $sex!~/^[MF]$/ ){
		print "Illeagal gender [$sex] please input M or F.\n";
		return;
	}
	if($passwd=~/[\x00-\x1f]/){
		print "Illeagal charactor found in password ".$`."[$&]$'\n";
		return;
	}
	if(length($passwd)<4){
		print "Password too short or long. please input 4-24bytes.!\n";
		return;
	}
	print $so pack("v2a24a24c", 0x7930,53, $userid,$passwd,($sex=="M")?1:0 );
	$so->flush();
	$buf=readso(2);
	if(unpack("v",$buf)!=0x7931){
		print "Packet error.\n";
		return;
	}
	$buf=readso(26);
	print "Account [$userid] ";
	if(unpack("v",$buf)!=0){
		print "creation failed. same account exists.\n";
	}else{
		print "is successfully created.\n";
	}
}
# アカウント削除
sub delaccount(){
	my($userid)= @_;
	print "** Are you really sure to DELETE account [$userid]? (y/n) ";
	if(lc(substr(<STDIN>,0,1)) ne "y"){
		return;
	}
	print $so pack("v2a24", 0x7932,28, $userid);
	$so->flush();
	$buf=readso(2);
	if(unpack("v",$buf)!=0x7933){
		print "Packet error.\n";
		return;
	}
	$buf=readso(26);
	print "Account [$userid] ";
	if(unpack("v",$buf)!=0){
		print "deletion failed. account dosent exist.\n";
	}else{
		print "is successfully DELETED.\n";
	}
	return;
}
# アカウントパスワード変更
sub changepasswd(){
	my($userid,$passwd)= @_;
	print $so pack("v2a24a24", 0x7934,52, $userid,$passwd);
	$so->flush();
	$buf=readso(2);
	if(unpack("v",$buf)!=0x7935){
		print "Packet error.\n";
		return;
	}
	$buf=readso(26);
	print "Account [$userid] ";
	if(unpack("v",$buf)!=0){
		print "password changing failed. account dosent exist.\n";
	}else{
		print "password successfully changed.\n";
	}
	return;
}
# READY信号待ち（未使用）
sub waitready(){
	$buf=readso(2);
	if(unpack("v",$buf)!=0x791f){
		print "Command stream error.\n";
		exit(9);
	}
	return 0;
}

# ソケットからデータを読み出す
sub readso(){
	my($len)=shift;
	my($buf);
	if( read($so,$buf,$len)<$len ){
		print "Socket read error.\n";
		exit(3);
	}
	return $buf;
}
