all: core.o socket.o timer.o grfio.o db.o lock.o

core.o: core.c core.h
socket.o: socket.c socket.h
timer.o: timer.c timer.h
grfio.o: grfio.c grfio.h
db.o: db.c db.h
lock.o: lock.h


clean:
	rm -f *.o
